# The Iris Dataset
The data set consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

The dataset contains a set of 150 records under five attributes - petal length, petal width, sepal length, sepal width and species.

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [230]:
#%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [231]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from keras.utils import np_utils
from keras.datasets import mnist
from sklearn.datasets import load_iris
from keras.models import Sequential
from keras.layers.core import Dense,Dropout,Activation,Flatten
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')
import tensorflow as tf

### Set random seed

In [232]:
tf.random.set_seed(42)

## Question 1

### Import dataset
- Import iris dataset
- Import the dataset using sklearn library

In [233]:
iris = load_iris()
list(iris.data)

[array([5.1, 3.5, 1.4, 0.2]),
 array([4.9, 3. , 1.4, 0.2]),
 array([4.7, 3.2, 1.3, 0.2]),
 array([4.6, 3.1, 1.5, 0.2]),
 array([5. , 3.6, 1.4, 0.2]),
 array([5.4, 3.9, 1.7, 0.4]),
 array([4.6, 3.4, 1.4, 0.3]),
 array([5. , 3.4, 1.5, 0.2]),
 array([4.4, 2.9, 1.4, 0.2]),
 array([4.9, 3.1, 1.5, 0.1]),
 array([5.4, 3.7, 1.5, 0.2]),
 array([4.8, 3.4, 1.6, 0.2]),
 array([4.8, 3. , 1.4, 0.1]),
 array([4.3, 3. , 1.1, 0.1]),
 array([5.8, 4. , 1.2, 0.2]),
 array([5.7, 4.4, 1.5, 0.4]),
 array([5.4, 3.9, 1.3, 0.4]),
 array([5.1, 3.5, 1.4, 0.3]),
 array([5.7, 3.8, 1.7, 0.3]),
 array([5.1, 3.8, 1.5, 0.3]),
 array([5.4, 3.4, 1.7, 0.2]),
 array([5.1, 3.7, 1.5, 0.4]),
 array([4.6, 3.6, 1. , 0.2]),
 array([5.1, 3.3, 1.7, 0.5]),
 array([4.8, 3.4, 1.9, 0.2]),
 array([5. , 3. , 1.6, 0.2]),
 array([5. , 3.4, 1.6, 0.4]),
 array([5.2, 3.5, 1.5, 0.2]),
 array([5.2, 3.4, 1.4, 0.2]),
 array([4.7, 3.2, 1.6, 0.2]),
 array([4.8, 3.1, 1.6, 0.2]),
 array([5.4, 3.4, 1.5, 0.4]),
 array([5.2, 4.1, 1.5, 0.1]),
 array([5.

## Question 2

### Get features and label from the dataset in separate variable
- you can get the features using .data method
- you can get the features using .target method

In [234]:
data1 = pd.DataFrame(data= np.c_[iris['data'], iris['target']],
                     columns= iris['feature_names'] + ['target_names'])
data1.head()
X= iris.data
y = iris.target
y.shape

(150,)

## Question 3

### Create train and test data
- use train_test_split to get train and test set
- set a random_state
- test_size: 0.25

In [235]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25, random_state=1)

## Question 4

### One-hot encode the labels
- convert class vectors (integers) to binary class matrix
- convert labels
- number of classes: 3
- we are doing this to use categorical_crossentropy as loss

In [236]:
y_train=np_utils.to_categorical( y_train, num_classes = 3)
y_test=np_utils.to_categorical( y_test, num_classes = 3)
y_train


array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1

In [237]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(112, 4)
(112, 3)
(38, 4)
(38, 3)


## Question 5

### Initialize a sequential model
- Define a sequential model

In [238]:
model=Sequential()

## Question 6

### Add a layer
- Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3
- Apply Softmax on Dense Layer outputs

In [239]:
model.add(Dense(6, input_dim=4, activation='relu'))
model.add(Dense(3, activation='softmax'))


## Question 7

### Compile the model
- Use SGD as Optimizer
- Use categorical_crossentropy as loss function
- Use accuracy as metrics

In [240]:
model.compile(loss='categorical_crossentropy',optimizer='SGD',metrics=['accuracy'])

## Question 8

### Summarize the model
- Check model layers
- Understand number of trainable parameters

In [241]:
print(model.summary())

Model: "sequential_15"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_30 (Dense)             (None, 6)                 30        
_________________________________________________________________
dense_31 (Dense)             (None, 3)                 21        
Total params: 51
Trainable params: 51
Non-trainable params: 0
_________________________________________________________________
None


## Question 9

### Fit the model
- Give train data as training features and labels
- Epochs: 100
- Give validation data as testing features and labels

In [242]:
model.fit(X_train,y_train,nb_epoch=100,validation_data=(X_test,y_test))


Train on 112 samples, validate on 38 samples
Epoch 1/100
112/112 [==============================] - 0s 2ms/step - loss: 1.0029 - accuracy: 0.6875 - val_loss: 1.0912 - val_accuracy: 0.2368
Epoch 2/100
112/112 [==============================] - 0s 357us/step - loss: 1.0008 - accuracy: 0.3661 - val_loss: 1.1034 - val_accuracy: 0.2368
Epoch 3/100
112/112 [==============================] - 0s 321us/step - loss: 0.9967 - accuracy: 0.5804 - val_loss: 1.0999 - val_accuracy: 0.2368
Epoch 4/100
112/112 [==============================] - 0s 357us/step - loss: 0.9947 - accuracy: 0.4375 - val_loss: 1.0943 - val_accuracy: 0.2368
Epoch 5/100
112/112 [==============================] - 0s 393us/step - loss: 0.9901 - accuracy: 0.4018 - val_loss: 1.0885 - val_accuracy: 0.2368
Epoch 6/100
112/112 [==============================] - 0s 357us/step - loss: 0.9874 - accuracy: 0.3661 - val_loss: 1.0880 - val_accuracy: 0.2368
Epoch 7/100
112/112 [==============================] - 0s 357us/step - loss: 0.9852 - a

Epoch 57/100
112/112 [==============================] - 0s 286us/step - loss: 0.8379 - accuracy: 0.6964 - val_loss: 0.9521 - val_accuracy: 0.5789
Epoch 58/100
112/112 [==============================] - 0s 286us/step - loss: 0.8348 - accuracy: 0.6964 - val_loss: 0.9549 - val_accuracy: 0.5789
Epoch 59/100
112/112 [==============================] - 0s 286us/step - loss: 0.8317 - accuracy: 0.6964 - val_loss: 0.9460 - val_accuracy: 0.5789
Epoch 60/100
112/112 [==============================] - 0s 321us/step - loss: 0.8275 - accuracy: 0.6964 - val_loss: 0.9402 - val_accuracy: 0.5789
Epoch 61/100
112/112 [==============================] - 0s 321us/step - loss: 0.8245 - accuracy: 0.6964 - val_loss: 0.9382 - val_accuracy: 0.5789
Epoch 62/100
112/112 [==============================] - 0s 286us/step - loss: 0.8220 - accuracy: 0.6964 - val_loss: 0.9336 - val_accuracy: 0.5789
Epoch 63/100
112/112 [==============================] - 0s 286us/step - loss: 0.8214 - accuracy: 0.6964 - val_loss: 0.9300 -

## Question 10

### Make predictions
- Predict labels on one row

In [243]:
single_test = X_test[10]
single_test = single_test.reshape(1,4)
model.predict_classes(single_test)

array([2], dtype=int64)

### Compare the prediction with actual label
- Print the same row as done in the previous step but of actual labels

In [244]:
print(X_test[10])
print(y_test[10])

[5.6 2.7 4.2 1.3]
[0. 1. 0.]




Conclusion:
Model has predicted value accurately.



# Stock prices dataset
The data is of tock exchange's stock listings for each trading day of 2010 to 2016.

## Description
A brief description of columns.
- open: The opening market price of the equity symbol on the date
- high: The highest market price of the equity symbol on the date
- low: The lowest recorded market price of the equity symbol on the date
- close: The closing recorded price of the equity symbol on the date
- symbol: Symbol of the listed company
- volume: Total traded volume of the equity symbol on the date
- date: Date of record

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [245]:
#%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [246]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from keras.utils import np_utils
from keras.datasets import mnist
from sklearn.datasets import load_iris
from keras.models import Sequential
from keras.layers.core import Dense,Dropout,Activation,Flatten
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')
import tensorflow as tf

### Set random seed

In [247]:
tf.random.set_seed(42)

## Question 1

### Load the data
- load the csv file and read it using pandas
- file name is prices.csv

In [248]:
# run this cell to upload file if you are using google colab
#from google.colab import files
#files.upload()

In [249]:
data = pd.read_csv('prices.csv')
data.head()

date symbol        open       close         low        high  \
0  2016-01-05 00:00:00   WLTW  123.430000  125.839996  122.309998  126.250000   
1  2016-01-06 00:00:00   WLTW  125.239998  119.980003  119.940002  125.540001   
2  2016-01-07 00:00:00   WLTW  116.379997  114.949997  114.930000  119.739998   
3  2016-01-08 00:00:00   WLTW  115.480003  116.620003  113.500000  117.440002   
4  2016-01-11 00:00:00   WLTW  117.010002  114.970001  114.089996  117.330002   

      volume  
0  2163600.0  
1  2386400.0  
2  2489500.0  
3  2006300.0  
4  1408600.0

In [250]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 851264 entries, 0 to 851263
Data columns (total 7 columns):
date      851264 non-null object
symbol    851264 non-null object
open      851264 non-null float64
close     851264 non-null float64
low       851264 non-null float64
high      851264 non-null float64
volume    851264 non-null float64
dtypes: float64(5), object(2)
memory usage: 45.5+ MB


In [251]:
data.shape

(851264, 7)

## Question 2

### Drop columnns
- drop "date" and "symbol" column from the data

In [252]:
data = data.drop(['date','symbol'],axis=1)

In [253]:
data.head(10)

open       close         low        high     volume
0  123.430000  125.839996  122.309998  126.250000  2163600.0
1  125.239998  119.980003  119.940002  125.540001  2386400.0
2  116.379997  114.949997  114.930000  119.739998  2489500.0
3  115.480003  116.620003  113.500000  117.440002  2006300.0
4  117.010002  114.970001  114.089996  117.330002  1408600.0
5  115.510002  115.550003  114.500000  116.059998  1098000.0
6  116.459999  112.849998  112.589996  117.070000   949600.0
7  113.510002  114.379997  110.050003  115.029999   785300.0
8  113.330002  112.529999  111.919998  114.879997  1093700.0
9  113.660004  110.379997  109.870003  115.870003  1523500.0

## Question 3

### Take initial rows
- Take first 1000 rows from the data
- This step is done to make the execution faster

In [254]:
data_sample = data.head(1000)

## Question 4

### Get features and label from the dataset in separate variable
- Take "open", "close", "low", "high" columns as features
- Take "volume" column as label
- Normalize label column by dividing it with 1000000

In [255]:
data_sample['volume'] = data_sample['volume'] / 1000000

y = data_sample['volume']
X = data_sample.drop('volume',axis=1)



In [256]:
y.head(10)


0    2.1636
1    2.3864
2    2.4895
3    2.0063
4    1.4086
5    1.0980
6    0.9496
7    0.7853
8    1.0937
9    1.5235
Name: volume, dtype: float64

## Question 5

### Convert data
- Convert features and labels to numpy array
- Convert their data type to "float32"

In [257]:
X_arr=np.array(X).astype('float32')
y_arr=np.array(y).astype('float32')
print(type(X_arr))
print(type(y_arr))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


## Question 6

### Normalize data
- Normalize features
- Use tf.math.l2_normalize to normalize features
- You can read more about it here https://www.tensorflow.org/api_docs/python/tf/math/l2_normalize

In [258]:
X_arr=tf.nn.l2_normalize(X_arr, axis=None, epsilon=1e-12, name=None)


In [259]:
print(X_arr)
print(y_arr)

tf.Tensor(
[[0.02202893 0.02245905 0.02182904 0.02253223]
 [0.02235197 0.0214132  0.02140606 0.02240551]
 [0.0207707  0.02051548 0.02051191 0.02137037]
 ...
 [0.00505436 0.00513467 0.00499903 0.00514181]
 [0.00785282 0.00799559 0.0078082  0.00799738]
 [0.00643931 0.00662849 0.00642682 0.00664455]], shape=(1000, 4), dtype=float32)
[2.163600e+00 2.386400e+00 2.489500e+00 2.006300e+00 1.408600e+00
 1.098000e+00 9.496000e-01 7.853000e-01 1.093700e+00 1.523500e+00
 1.653900e+00 9.443000e-01 7.449000e-01 7.038000e-01 5.631000e-01
 8.961000e-01 6.804000e-01 7.499000e-01 5.742000e-01 6.948000e-01
 8.963000e-01 9.563000e-01 9.971000e-01 1.200500e+00 1.725200e+00
 1.946000e+00 1.319500e+00 9.224000e-01 1.185100e+00 9.215000e-01
 4.409000e-01 1.244300e+00 6.813000e-01 4.112000e-01 4.473000e-01
 5.592000e-01 4.599000e-01 9.716000e-01 6.941000e-01 1.159600e+00
 8.847000e-01 6.920000e-01 8.980000e-01 8.445000e-01 7.965000e-01
 4.168000e-01 5.902000e-01 4.951000e-01 5.158000e-01 5.621000e-01
 8.09300

 2.133200e+00 1.982400e+00 3.715280e+01 6.568600e+00 5.604300e+00]


## Question 7

### Define weight and bias
- Initialize weight and bias with tf.zeros
- tf.zeros is an initializer that generates tensors initialized to 0
- Specify the value for shape

In [260]:
W = tf.zeros(shape=[4,1])
b = tf.zeros(shape=[1])

## Question 8

### Get prediction
- Define a function to get prediction
- Approach: prediction = (X * W) + b; here is X is features

In [261]:
@tf.function
def prediction(x, w, b):
    xw_matmul = tf.matmul(x, w)
    y = tf.add(xw_matmul, b)
    return y

### Calculate loss
- Calculate loss using predictions
- Define a function to calculate loss
- We are calculating mean squared error

In [262]:
@tf.function
def loss(y_actual, y_predicted):
    diff = y_actual - y_predicted
    sqr = tf.square(diff)
    avg = tf.reduce_mean(sqr)
    return avg

## Question 9

### Define a function to train the model
1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [263]:
@tf.function
def train(x, y_actual, w, b, learning_rate=0.01):    
    #Record math ops on 'tape' to calculate loss
    with tf.GradientTape() as t:
        t.watch([w,b])    
        current_prediction = prediction(x, w, b)
        current_loss = loss(y_actual, current_prediction)
    #Calculate Gradients for Loss w.r.t Weights and Bias
    dw, db = t.gradient(current_loss,[w, b])
    #Update Weights and Bias
    w = w - learning_rate*dw
    b = b - learning_rate*db
    return w, b

## Question 10

### Train the model for 100 epochs 
- Observe the training loss at every iteration

In [264]:
for i in range(100):
    W, b = train(X_arr, y_arr, W, b)
    print('W=',W,'b=',b)
    print('Current Loss on iteration', i, loss(y_arr, prediction(X_arr, W, b)).numpy())

W= tf.Tensor(
[[0.00126439]
 [0.00126667]
 [0.00125157]
 [0.00127704]], shape=(4, 1), dtype=float32) b= tf.Tensor([0.10628445], shape=(1,), dtype=float32)
Current Loss on iteration 0 236.16774
W= tf.Tensor(
[[0.00250346]
 [0.00250799]
 [0.00247808]
 [0.00252851]], shape=(4, 1), dtype=float32) b= tf.Tensor([0.210442], shape=(1,), dtype=float32)
Current Loss on iteration 1 235.09312
W= tf.Tensor(
[[0.00371773]
 [0.00372445]
 [0.00368004]
 [0.00375493]], shape=(4, 1), dtype=float32) b= tf.Tensor([0.31251523], shape=(1,), dtype=float32)
Current Loss on iteration 2 234.06105
W= tf.Tensor(
[[0.00490768]
 [0.00491655]
 [0.00485793]
 [0.0049568 ]], shape=(4, 1), dtype=float32) b= tf.Tensor([0.41254583], shape=(1,), dtype=float32)
Current Loss on iteration 3 233.06989
W= tf.Tensor(
[[0.00607382]
 [0.0060848 ]
 [0.00601224]
 [0.0061346 ]], shape=(4, 1), dtype=float32) b= tf.Tensor([0.5105747], shape=(1,), dtype=float32)
Current Loss on iteration 4 232.11801
W= tf.Tensor(
[[0.0072166 ]
 [0.007229

W= tf.Tensor(
[[0.04320902]
 [0.04328716]
 [0.04277094]
 [0.04364148]], shape=(4, 1), dtype=float32) b= tf.Tensor([3.6332057], shape=(1,), dtype=float32)
Current Loss on iteration 56 211.86465
W= tf.Tensor(
[[0.04360811]
 [0.04368697]
 [0.04316599]
 [0.04404457]], shape=(4, 1), dtype=float32) b= tf.Tensor([3.6667848], shape=(1,), dtype=float32)
Current Loss on iteration 57 211.75298
W= tf.Tensor(
[[0.04399921]
 [0.04407877]
 [0.04355311]
 [0.04443958]], shape=(4, 1), dtype=float32) b= tf.Tensor([3.699692], shape=(1,), dtype=float32)
Current Loss on iteration 58 211.64569
W= tf.Tensor(
[[0.04438247]
 [0.04446273]
 [0.04393248]
 [0.04482667]], shape=(4, 1), dtype=float32) b= tf.Tensor([3.7319407], shape=(1,), dtype=float32)
Current Loss on iteration 59 211.5427
W= tf.Tensor(
[[0.04475804]
 [0.04483898]
 [0.04430425]
 [0.04520601]], shape=(4, 1), dtype=float32) b= tf.Tensor([3.763544], shape=(1,), dtype=float32)
Current Loss on iteration 60 211.44377
W= tf.Tensor(
[[0.0451261 ]
 [0.045207

### Observe values of Weight
- Print the updated values

In [265]:
print('Weight=',W )

Weight= tf.Tensor(
[[0.0547828 ]
 [0.0548819 ]
 [0.05422734]
 [0.05533116]], shape=(4, 1), dtype=float32)


### Observe values of Bias
- Print the updated values

In [266]:
print('Bias=',b )

Bias= tf.Tensor([4.607657], shape=(1,), dtype=float32)
